### ISSUE TITLE
User can move their car around.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Driving-Game#2]

**Comment by gdegas** [comment]
# Motivation
User can see the direction the car is moving towards.

# Tasks
- [x] Create a car class with a constructor:
- [x] Create method on car class that starts the car
- [x] Create turn and accelerate methods
- [x] Add even listeners to arrow keys that change the direction of the car
